### ISSUE TITLE
Mint DAO Beta version bugs report

### ISSUE THREAD

**Issue by Linklinkguan** [carboclan/y3d-protocol#42]
- [ ] `your current yCrv balance:  0` --> `your current yyCrv balance:  0`

- [ ] total minted yyCrv & total minted USDT shows wrong result

- [ ] withdraw feature doesn't work

![image](https://user-images.githubusercontent.com/10827774/92299747-cef4e200-ef87-11ea-8e74-728e4c577bc8.png)

**Comment by lychees** [comment]
Solved..
